name: brambl_tetra
description: Dart SDK for the Topl Tetra blockchain
version: 0.1.0
homepage: https://github.com/Topl/brambl-tetra-dart

environment:
  sdk: '>=2.17.1 <3.0.0'

#dependencies:
#   path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.2.0
